name: Node.js Package
# 监测图床分支，2020年10月后github新建仓库默认分支改为main，记得更改
on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      - name: 读取生成时间戳作为版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: package.json
          property: date
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

